### ISSUE TITLE
Hosting

### ISSUE THREAD

**Issue by ghost** [milux/ctldap#1]
Wir verwenden das von ChurchTools administrierte Produkt. Gibt es eine Möglichkeit, deinen LDAP Wrapper damit zu verwenden oder sind wir gezwungen, wieder auf die self-hosted Variante umzusteigen?

**Comment by milux** [comment]
Ich habe schon vor Wochen eine Integration der API in ChurchTools vorgeschlagen. Da ich auch kürzlich für 2 Monate (war absichtlich nur so lange... :wink:) Angestellter der CT Innovations GmbH war, darf ich noch an der einen oder anderen Stelle mitmachen und bin quasi Hilfs-Entwickler.
Allerdings wollten die anderen Entwickler, dass ich meinen Code in ihre API einbaue, die meiner Meinung nach weder qualitativ noch technisch angemessen für diese Aufgabe ist. Daher gab es einige Verstimmungen, und gerade habe ich fast keine Zeit, weswegen der Prozess zum Stillstand gekommen ist.
Da das aber nunmal nicht meine Software ist, und ich froh sein kann, dort mitarbeiten zu dürfen, werde ich mich so oder so ihren Wünschen anpassen müssen, um eine vernünftige Lösung für alle Kunden zu finden.
Wenn das geht, gib uns bitte noch ein paar Wochen, uns zusammen zu raufen. Ich hoffe dann haben wir eine Lösung, die allen nützt.

**Comment by ghost** [comment]
Danke für die Info und für deine Arbeit! Es würde mich (und einen Teil unserer 350 CT User) auf jeden Fall freuen, wenn es da bald eine Lösung gäbe. Wir warten gespannt...

**Comment by milux** [comment]
Ich hab' am Wochenende nochmal ein paar Stunden Arbeit investiert.
Gestern wurde die Kompromiss-Lösung in den Hauptzweig aufgenommen.
Voraussichtlich gibt es am kommenden Montag ein ChurchTools-Release mit eingebautem Support für ctldap.
Sobald ich die neue Version 2.0 von ctldap nochmal geprüft habe, werde ich sie hier veröffentlichen, und dann steht ctldap für alle CT-User zur Verfügung.

**Comment by tomzi8571** [comment]
Hi @milux, ichwollte fragen, wie man auf die ldap schnittstelle beim CT hosting jetzt zugreifen kann? Welcher Port wird verwendet? Gibt es einen Authentifizierung? Kann man sonst noch entwas konfigurieren über das UI?
Ich versuchte per linux mit ldapvi auf den unseren gehosteten server zuzugreifen. Jedoch kein Erfolg...

**Comment by ghost** [comment]
@milux schade, dass es nur die Kompromiss-Lösung wurde, aber vielen Dank, dass du uns überhaupt eine Lösung geschaffen hast!

@tomzi8571 unsere Installation hat noch kein Update bekommen.

**Comment by milux** [comment]
@tomzi8571 Um die Schnittstelle zu verwenden, musst du den LDAP-Wrapper auf einem Gerät **in deinem Netzwerk** laufen lassen. Wir verwenden z.B. einen Raspberry Pi mit Raspbian dafür. Das ist auch grundsätzlich sehr sinnvoll, weil **LDAP sich kaum vernünftig verschlüsseln lässt**, daher sollte der Wrapper auf jeden Fall im selben Netzwerk sein wie der LDAP-Client (d.h. NextCloud oder sowas ähnliches).
Der Wrapper greift dann auf ChurchTools zu, mit den Benutzerdaten eines CT-Nutzers, der die Rechte "Personenberechtigungen verwalten" und "ChruchDB sehen" haben muss, zieht sich die Benutzer und Gruppen, und stellt sie über eine LDAP-Schnittstelle zur Verfügung.

Die neue Version ist zwar soweit fertig, aber es fehlen noch ein paar Anpassungen an den Installations-Skripten. Wenn ich soweit bin, wird die neue Version hier online gehen.

Die Schnittstellen wurden im Übrigen mit dem Release 3.25.x gestern im Tagesverlauf ausgerollt.

**Comment by tomzi8571** [comment]
Aha, ok! Da wollt ich doch gleich mal nachfragen, ob du vielleicht auch ein ldap query caching eingebaut hast. zb dass der wrapper nur alle (zb 5min) realdaten abfrägt, um die Performance hoch zu halten?

**Comment by milux** [comment]
Hatte ich mir überlegt, aber die Verarbeitung der Queries ist derart simpel und schnell, dass es sich nicht im geringsten lohnt, einen richtigen Query-Cache zu verwenden. Außerdem würde dadurch der benötigte Speicher und die Komplexität das Systems deutlich zunehmen, was am Ende die Performance evtl. sogar verschlechtern würde.
Die Daten von CT werden aber in der Tat gecached, denn die sind das echte Bottleneck. Per default sind die Daten nach Abruf nur 10 Sekunden gültig, aber du kannst die Caching-Zeit in der ctldap.config an deine eigenen Vorstellungen anpassen.
Die Authentifizierung geht aus Sicherheitsgründen immer direkt an das CT-Backend, sodass eine Passwortänderung oder Sperrung unmittelbar wirksam wird.

**Comment by milux** [comment]
CTLDAP v2.0 wurde soeben veröffentlicht, viel Spaß beim Verwenden!
In nächster Zeit wird noch ein Video-Tut folgen.
Falls Probleme auftauchen, bitte neue Issues dafür aufmachen, dieses Issue ist hiermit **closed**.
