### ISSUE TITLE
Case-insensitive search missing

### ISSUE THREAD

**Issue by sscholl** [milux/ctldap#11]
The search is case sensitiv. Users can't login with Test1, but with test1 if user is test1.

```
$ docker-compose run test ldapsearch -H ldap://ldap:1389 -x -D cn=root,ou=users,o=**** -w ^****************
-LLL -b o=**** '(&(&(objectclass=ctperson))(|(cn=*test1*)))'
dn: cn=test1.user,ou=users,o=****
cn: test1.user
displayname: Test1 User
id: 1507
uid: test1.user
nsuniqueid: u1507
givenname: Test1
sn: User
email: test@*****.de
mail: test@*****.de
objectclass: CTPerson
memberof: cn=it,ou=groups,o=****

$ docker-compose run test ldapsearch -H ldap://ldap:1389 -x -D cn=root,ou=users,o=****  -w ******************
-LLL -b o=**** '(&(&(objectclass=ctperson))(|(cn=*Test1*)))'

```

**Comment by Seb9mann** [comment]
Same problem here. What to do?

**Comment by a-schild** [comment]
We see this also as a problem when searching for group names.
When we try to share with groups in Nextcloud 15, the search for matching groups is done case sensitiv, which is "not nice" for the users, since they need to know which upper/lowercase the group was created in ct

**Comment by milux** [comment]
Solution from https://github.com/ldapjs/node-ldapjs/issues/156 has been copy-pasted somewhere in the ctldap-ms fork, so this is done.
