### ISSUE TITLE
Paging

### ISSUE THREAD

**Issue by sscholl** [milux/ctldap#2]
Hallo,
tolles Projekt! Leider kann ich das für eine Anbindung an Rocket.Chat nicht nutzen, da Rocket.Chat Paging erwartet. Kann das einfach erweitert werden?

Danke,
Simon Scholl

**Comment by milux** [comment]
Ich fürchte, da muss ich dich enttäuschen. :(
Ich hab' schon Warnungen deswegen mit anderen Clients bekommen, der Server scheint paging-Anforderungen einfach zu ignorieren.
Da dafür eine externe library eingesetzt wird, müsste man sich mit dieser Frage an den Maintainer dieses Repos wenden:
https://github.com/mcavage/node-ldapjs
Leider gibt's da auch schon eine ganze Weile keine Updates mehr...

**Comment by sscholl** [comment]
Danke. Die neuere Version hat das Problem auch nicht mehr...
