### ISSUE TITLE
Nextcloud group assignements get lost during ct upgrade

### ISSUE THREAD

**Issue by a-schild** [milux/ctldap#20]
- user is actively using nextcloud with the ldap integration
- When ct is upgrading and the user is active in nextcloud during the upgrade, the group assignements in nextcloud of the active user get lost

- After some time the group assignement in nextcloud are OK again

**Comment by milux** [comment]
Hello @a-schild, is there any permanent issue due to this?
Because if this is only causing temporary issues for the narrow time window of an update (for us this is typically done at night by the auto updater), then this is going to be a nofix-issue.

**Comment by milux** [comment]
Closing this assuming that it describes a very rare effect not causing permanent issues.
