### ISSUE TITLE
Retrieve LDAP Information with authenticated user

### ISSUE THREAD

**Issue by teleharry** [milux/ctldap#30]
I have some apps which try to retrieve information by its authenticated user. So the ldap wrapper only allows this by the root dn. Could this somehow be extended to any user who is authenticated?

**Comment by milux** [comment]
Obsolete, because 3.0.0 works with tokens therefore doesn't use normal authentication anymore.
Theoretically, it would have been possible, but it would re-introduce some clutter (cookie handling) etc. that I have happily removed these days...
