### ISSUE TITLE
dockerhub outdated 

### ISSUE THREAD

**Issue by smehrbrodt** [milux/ctldap#49]
Can you please update the image at https://registry.hub.docker.com/r/milux/ctldap/ ?
It hasn't been updated in six months.

**Comment by a-schild** [comment]
Could be automated via github actions...

**Comment by milux** [comment]
> Can you please update the image at https://registry.hub.docker.com/r/milux/ctldap/ ? It hasn't been updated in six months.

Is there any specific reason like e.g. a CVE in a dependency which requires an update?

**Comment by smehrbrodt** [comment]
Fixes that were committed here, but are not in the image. I was esp. looking for commit f1edc22af55be8281dcc8c20a7c0b3ad5196f589 which I hope would fix an issue with Synology.

But now I see that the last docker update was after that commit, so it's probably already there.

**Comment by milux** [comment]
> Fixes that were committed here, but are not in the image. I was esp. looking for commit [f1edc22](https://github.com/milux/ctldap/commit/f1edc22af55be8281dcc8c20a7c0b3ad5196f589) which I hope would fix an issue with Synology.
> 
> But now I see that the last docker update was after that commit, so it's probably already there.

It most certainly is. :wink: 
I'm not aware of any commits that happened after releasing the last version, see also the tags on Docker Hub.

**Comment by milux** [comment]
BTW: Our instance is running on a Synology DS716+II without issues, maybe you want to be a little more specific about your Synology problem. :wink:

**Comment by smehrbrodt** [comment]
> BTW: Our instance is running on a Synology DS716+II without issues, maybe you want to be a little more specific about your Synology problem. 😉

Alright, I submitted #50 detailing my problem.
